apiVersion: v1
kind: Service
metadata:
  name: thc1006-web
  namespace: thc1006-web
  labels:
    app.kubernetes.io/name: thc1006-web
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: thc1006-web
